### PR TITLE
Add ts declaration file

### PR DESCRIPTION
**Pull request by sroussey**
There are a lot of ways to go about this, but the easiest to to just write the file since this project is so small!

### CODE REVIEW

**Comment by sroussey** [comment]
Should close https://github.com/ashvardanian/SimSIMD/issues/47

**Comment by ashvardanian** [comment]
Do you by any chance know, why NPM publish action fails in CI, @sroussey? The CI fails, but the error isn't informative, and it doesn't happen when I push from my machine.

**Comment by sroussey** [comment]
Did I change that? I have separate branch for those changes, but it's not ready yet. Thought I can cherry pick them.

**Comment by ashvardanian** [comment]
No, @sroussey it started happening long before you joined the project, but I haven't resolved it yet.

**Comment by sroussey** [comment]
I’ll have a look

**Pull request merged**
