### PR TITLE
Change build release process

### PR DESCRIPTION
**Pull request by sroussey**
I haven't tested the final npm release, so we should coordinate in case something goes back when you run this.

Also, later, we can take out the running on `test-**` branches (though those don't npm publish) (see https://github.com/sroussey/SimSIMD/pull/1).

### CODE REVIEW

**Comment by ashvardanian** [comment]
I think we should pre-build Arm binaries as well.

**Comment by sroussey** [comment]
It does for Mac, but not for windows or Linux. I’ll give it a try!

**Comment by sroussey** [comment]
OK, I was able to cross compile arm64 on the ubuntu build process.

Note, unlike python wheels, if the user platform is not covered, it will still just build on install (assuming that install scripts are allowed -- bun does not allow that, and others tend to not allow that these days either, but it is still the default for npm).

**Comment by sroussey** [comment]
I have gone through building and publishing (using my own name `@sroussey/simsimd`) in order to test end-to-end. Which is good as I found some issues.

Anyhow, I consider this complete. :)

**Comment by ashvardanian** [comment]
Looks scary, @sroussey, but let's try this 🤗

**Pull request merged**
